# Generated by Django 3.2.8 on 2021-10-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjsondwisql',
            options={},
        ),
    ]
