# Generated by Django 3.2.8 on 2021-10-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_importjsondwisql_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjsondwisql',
            options={'managed': False},
        ),
    ]
